#!/bin/sh 

# 
# This script is loading modules in the kernel. 
# 

kernel=`uname -r | grep 2.4`

if [ ${kernel} ]
    then
        module=ipcdrv.o
        mname=${module%.o}
    else
        module=`find *.ko`
        mname=${module%.ko}
fi

if [ ${module} ]
    then
        echo Find ${module} - kernel module.
    else
        echo No kernel module found. ${module}
        exit
fi

was_loaded=`/sbin/lsmod | cut -c 1-6 | grep ipcdrv`

if [ ${was_loaded} ]
    then
        echo Remove loaded module: ${module}
        /sbin/rmmod ipcdrv
    else
        echo Loading module: ${module}
fi

/sbin/insmod ./$module $* || exit 1

sleep 1

devfiles=`ls /dev/* | grep ipc`

#echo ${devfiles}

chmod -v 666 ${devfiles}
