#pragma once
#ifdef _UNICODE
typedef wchar_t			BRDCHAR;
#define _BRDC(x)		L ## x
#define BRDC_strlen		wcslen
#define BRDC_strcpy		wcscpy
#define BRDC_strncpy	wcsncpy
#define BRDC_strcmp		wcscmp
#define BRDC_stricmp	_wcsicmp
#define BRDC_strnicmp	wcsnicmp
#define BRDC_strncmp	wcsncmp
#define BRDC_strcat		wcscat
#define BRDC_strchr		wcschr
#define BRDC_strstr		wcsstr
#define BRDC_strtol		wcstol
#define BRDC_strtoul	wcstoul
#define BRDC_strtod		wcstod
#define BRDC_strtok		wcstok
#define BRDC_atol		_wtol
#define BRDC_atoi		_wtoi
#define BRDC_atoi64		_wtoi64
#define BRDC_strtoui64	_wcstoui64
#define BRDC_atof		_wtof
#define BRDC_strlwr		_wcslwr
#define BRDC_itoa		_itow
#define BRDC_printf		wprintf
#define BRDC_fprintf	fwprintf
#define BRDC_fscanf		fwscanf
#define BRDC_sprintf	swprintf
#define BRDC_vsprintf	vswprintf
#define BRDC_sscanf		swscanf
#define BRDC_fopen		_wfopen
#define BRDC_freopen	_wfreopen
#define BRDC_fdopen		_wfdopen
#define BRDC_sopen		_wsopen
#define BRDC_open		_wopen
#define BRDC_fgets		fgetws
#define BRDC_fputs		fputws
#define BRDC_fgetc		fgetwc
#define BRDC_getenv		_wgetenv
#define BRDC_main		wmain
#define BRDC_toupper	towupper
#define BRDC_tolower	towlower
#define BRDC_isspace	iswspace
#define BRDC_isdigit	iswdigit
#define BRDC_isalnum	iswalnum
#define BRDC_isxdigit	iswxdigit
#define BRDC_cputs      _cputws
#define BRDC_cscanf     _cwscanf
#define BRDC_fputchar   _fputwchar
#define BRDC_fgetchar   _fgetwchar
#define BRDC_flushall   flushall
#define BRDC_putch      _putwch
#define BRDC_cgets      _cgetws
#define BRDC_puts		_putws
#define BRDC_gets(str)		_getws_s( str, 65536 )		
#define BRDC_tmpnam		_wtmpnam
#define BRDC_perror		_wperror
#define BRDC_getcwd		_wgetcwd
#define BRDC_getdcwd	_wgetdcwd
#define BRDC_mkdir		_wmkdir
#define BRDC_chdir		_wchdir
#define BRDC_rmdir		_wrmdir
#define BRDC_access		_waccess
#define BRDC_chmod		_wchmod
#define BRDC_creat		_wcreat
#define BRDC_mktemp		_wmktemp
#define BRDC_remove		_wremove
#define BRDC_rename		_wrename
#define BRDC_findfirst	_wfindfirst
#define BRDC_findnext	_wfindnext
#define BRDC_asctime	_wasctime
#define BRDC_ctime		_wctime
#define	BRDC_strftime	wcsftime
#define BRDC_stat		_wstat
#else
typedef char			BRDCHAR;
#define _BRDC(x)		x
#define BRDC_strlen		strlen
#define BRDC_strcpy		strcpy
#define BRDC_strncpy	strncpy
#define BRDC_strcmp		strcmp
#define BRDC_stricmp	_stricmp
#define BRDC_strnicmp	_strnicmp
#define BRDC_strncmp	strncmp
#define BRDC_strcat		strcat
#define BRDC_strchr		strchr
#define BRDC_strstr		strstr
#define BRDC_strtol		strtol
#define BRDC_strtoul	strtoul
#define BRDC_strtod		strtod
#define BRDC_strtok		strtok
#define BRDC_atol		atol
#define BRDC_atoi		atoi
#define BRDC_atoi64		_atoi64
#define BRDC_strtoui64	_strtoui64
#define BRDC_atof		atof
#define BRDC_strlwr		_strlwr
#define BRDC_itoa		_itoa
#define BRDC_printf		printf
#define BRDC_fprintf	fprintf
#define BRDC_fscanf		fscanf
#define BRDC_sprintf	sprintf
#define BRDC_vsprintf	vsprintf
#define BRDC_sscanf		sscanf
#define BRDC_fopen		fopen
#define BRDC_freopen	freopen
#define BRDC_fdopen		fdopen
#define BRDC_sopen		sopen
#define BRDC_open		_open
#define BRDC_filelength _filelength
#define BRDC_fgets		fgets
#define BRDC_fputs		fputs
#define BRDC_fgetc		fgetc
#define BRDC_getenv		getenv
#define BRDC_main		main
#define BRDC_toupper	toupper
#define BRDC_tolower	tolower
#define BRDC_isspace	isspace
#define BRDC_isdigit	isdigit
#define BRDC_isalnum	isalnum
#define BRDC_isxdigit	isxdigit
#define BRDC_cputs      cputs
#define BRDC_cscanf     cscanf
#define BRDC_fputchar   fputchar
#define BRDC_fgetchar   fgetchar
#define BRDC_flushall   flushall
#define BRDC_putch      putch
#define BRDC_cgets      cgets
#define BRDC_puts		puts
#define BRDC_gets(str)		gets_s( str, 65536 )
#define BRDC_tmpnam		tmpnam
#define BRDC_perror		perror
#define BRDC_getcwd		getcwd
#define BRDC_getdcwd	_getdcwd
#define BRDC_mkdir		mkdir
#define BRDC_chdir		chdir
#define BRDC_rmdir		rmdir
#define BRDC_access		access
#define BRDC_chmod		chmod
#define BRDC_creat		creat
#define BRDC_mktemp		mktemp
#define BRDC_remove		remove
#define BRDC_rename		rename
#define BRDC_findfirst	_findfirst
#define BRDC_findnext	_findnext
#define BRDC_asctime	asctime
#define BRDC_ctime		ctime
#define	BRDC_strftime	strftime
#define BRDC_stat		stat
#endif
